<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentJs</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>

    <artifactId>GDGame2HTMLJs</artifactId>
    <packaging>jar</packaging>
    
    <name>GDGame2HTMLJs</name>
    <url>http://www.allbinary.com/</url>

    <properties>
        <buildLabel>${project.version}</buildLabel>
        <inputPath>target\dependency</inputPath>
        <inputPath2>src\main\java\</inputPath2>
        <outputPath>..\..\..\platformx\html\GDGame2HTMLTempM\src</outputPath>
    </properties>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingPlayN2ExceptionJs</artifactId>
            <!--
            <artifactId>LoggingHTMLAllJs</artifactId>
            <artifactId>LoggingNoneJs</artifactId>
            <artifactId>LoggingHTML5ExceptionJs</artifactId>
            <artifactId>LoggingRemoteExceptionJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOnHTMLPlatformJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <exclusions>
                <exclusion>
                    <groupId>org.allbinary</groupId>
                    <artifactId>J2MEJsInteropCompatibilityJavaLibraryJs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.animation</groupId>
            <artifactId>AllBinaryHTML2ImageAnimationRotationJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ImageCacheJ2MEJavaLibraryJs</artifactId>    
<!--        
            <artifactId>ImageCacheJ2MEJavaLibraryJs</artifactId>    
            <artifactId>ImageCacheLazyJ2MEJavaLibraryJs</artifactId>
-->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ImageCacheBaseNonJ2MEJavaLibraryJs</artifactId>            
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AppNoneOpenGLESJavaLibraryJs</artifactId>            
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameInputPCJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDFormJavaLibraryJs</artifactId>
            <!--
            <artifactId>GDFormJavaLibraryJs</artifactId>
            <artifactId>GDYourFormJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MusicJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoSWTJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>OpenGLNoneOtherJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>OpenGLNoneOther2JavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ProgressJ2MEJavaLibraryJs</artifactId>
<!-- 
            <artifactId>ProgressJ2MEJavaLibraryJs</artifactId>
            <artifactId>ProgressLazyJ2MEJavaLibraryJs</artifactId>
-->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FormJMEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameScoresLocalJavaLibraryJs</artifactId>
<!--
            <artifactId>GameScoresLocalJavaLibraryJs</artifactId>
            <artifactId>GameScoresRemoteAndLocalJavaLibraryJs</artifactId>
-->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
<!--
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>XmlRpcJavaLibraryJs</artifactId>
            <version>${allbinary.platform.version}</version>
        </dependency>
            <artifactId>XmlRpcJavaLibraryJs</artifactId>
            <artifactId>YourXmlRpcJavaLibraryJs</artifactId>
-->
<!--
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FreeTTSJ2MEJavaLibraryJs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
-->
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameHTMLPlaynJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>    

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGamePreBaseJavaLibraryJs</artifactId>
            <!-- Game Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- Game Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AdvertisementClientNoneJavaLibraryJs</artifactId>
            <!--
            <artifactId>AndroidAdvertisementJavaLibraryJs</artifactId>            
            <artifactId>AdvertisementClientNoneJavaLibraryJs</artifactId>           
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameAndroidAdvertisementJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.multiplayer</groupId>
            <artifactId>AllBinaryGameClientBaseNullJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
            <!--
                <artifactId>GameLicensingOnlyNormalJavaLibraryJs</artifactId>
                <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
                <artifactId>GameLicensingInAppPurchaseJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchButtonMappingJavaLibraryJs</artifactId>
            <!--
            For HTML build it is already part of GameInputPCMotion
            <artifactId>NoTouchButtonJavaLibraryJs</artifactId>
            <artifactId>TouchButtonMappingJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>NoTouchButtonResourceAnimationJavaLibraryJs</artifactId>
            <!--
            <artifactId>NoTouchButtonResourceAnimationJavaLibraryJs</artifactId>
            <artifactId>TouchButtonResourceAnimationJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>TouchButtonResourceOpenGLESAnimationJavaLibraryJs</artifactId>
            <!--
            <artifactId>NoTouchButtonResourceAnimationJavaLibraryJs</artifactId>
            <artifactId>TouchButtonResourceAnimationJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
                
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameNoTouchJavaLibraryJs</artifactId>
            <!--
            <artifactId>GDGameNoTouchJavaLibraryJs</artifactId>
            <artifactId>GDGameTouchJavaLibraryJs</artifactId>
            -->
            <exclusions>
                <exclusion>
                    <artifactId>NoTouchButtonJavaLibraryJs</artifactId>
                    <groupId>org.allbinary</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGamePCClientInfoJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameHTMLJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameBaseJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameHTMLImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
            <!--
            <artifactId>GDGameHTMLImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
            <artifactId>GDGameLazyHTMLImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
            <artifactId>GDGameImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <exclusions>
                <exclusion>
                    <groupId>org.allbinary.animation</groupId>
                    <artifactId>AllBinaryHTMLImageAnimationRotationJavaLibraryJs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>j2me-json</groupId>
            <artifactId>jsonJs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ABDKPlaynJavaLibraryJs</artifactId>
            <version>2.0</version>
            <optional>true</optional>
        </dependency>
        
    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <id>npm-install-typescript</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <arguments>
                                <argument>/c</argument>
                                <argument>npm</argument>
                                <argument>install</argument>
                                <argument>typescript</argument>
                                <argument>--no-save</argument>
                                <argument>--no-audit</argument>
                                <argument>--no-fund</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tsc-compile</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <!-- Uses the path from tsconfig.json instead of -p path; ignore tsc errors so the build continues -->
                            <arguments>
                                <argument>/c</argument>
                                <!--                                <argument>npx tsc</argument>-->
                                <argument>npx tsc || exit 0</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.1.2</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-pluginJs</artifactId>
                <executions>
                    <execution>
                        <id>sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
                            <!--
                            <outputDirectory>${project.build.directory}/sources</outputDirectory>
                            -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Delete output directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-pluginJs</artifactId>
                <version>2.4.1</version>
                <configuration>
                    <followSymLinks>false</followSymLinks>
                    <filesets>
                        <fileset>
                            <directory>${outputPath}</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-resources-pluginJs</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${outputPath}</outputDirectory>
                            <resources>          
                                <resource>
                                    <directory>${inputPath}</directory>
                                    <filtering>true</filtering>
                                </resource>
                                <resource>
                                    <directory>${inputPath2}</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>              
                        </configuration>            
                    </execution>
                </executions>
            </plugin>
      
        </plugins>
    </build>

</project>

