<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParent</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>

    <artifactId>GDGame2JsHTMLPlatformP</artifactId>
    <packaging>pom</packaging>

    <name>GDGame2JsHTMLPlatformP</name>
    <url>http://www.allbinary.com/</url>

    <properties>
        <buildLabel>${version}</buildLabel>
    </properties>

    <modules>

        <!--
        <module>../GDGameTouchHTMLM</module>
        -->
        <module>../GDGameHTMLResourcesJavaLibraryJsM</module>
        <module>../GDGame2JsHTMLM</module>
        <module>../GDGameHTMLJavaLibraryJsM</module>
        <module>../../../platformx/html/GDGame2JsHTMLTempM</module>
        <module>../GDGameHTMLPlaynJavaLibraryJsM</module>
        <!--
        <module>../GDGamePlayNWarM</module>
        -->
        <module>../GDGame2ForJsPlayNM</module>
    </modules>

</project>
