<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentTs</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version End -->
    </parent>
    
    <artifactId>GDGameThreedBaseJavaLibraryTs</artifactId>
    <packaging>jar</packaging>
    
    <name>GDGameThreedBaseJavaLibraryTs</name>
    <url>http://www.allbinary.com</url>

    <properties>
        <buildLabel>${version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>

<!--
        <dependency>
            <groupId>com.sun</groupId>
            <artifactId>GDLWUITJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
-->

        <!--
        -->
        <dependency>
            <groupId>org.mapgenerator</groupId>
            <artifactId>TileMapGeneratorJavaLibraryMTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.mapgenerator.dungeon</groupId>
            <artifactId>DungeonGeneratorJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <!--
        -->

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOptionalBasePlatformJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LogJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ImageCacheLazyJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoSystemJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedBaseJ2SEWithSWTJOGLJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>OpenGLNoneJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedJ2SEWithSWTJOGLResourceJavaLibraryTs</artifactId>
            
<!--            <groupId>org.allbinary</groupId>
            <artifactId>AppNoneOpenGLESJavaLibraryTs</artifactId>-->
            <version>${allbinary.platform.version}</version>
            <optional>true</optional>
        </dependency>
        

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FormJMEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>J2SEForJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameScoresLocalJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MusicJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FullScreenNoneJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AllBinaryToMin3dInputJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AllBinaryToMin3dInputJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AllBinaryToMin3dJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
 
        <dependency>
            <groupId>min3d</groupId>
            <artifactId>Min3dForAndroidPlatformJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameGeneratedJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.multiplayer</groupId>
            <artifactId>AllBinaryGameClientBaseNullJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <!--
            <artifactId>AllBinaryGameClientBaseJavaLibraryTs</artifactId>
            -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameTouchJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedPreBaseJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <optional>true</optional>            
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameResourceJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>
                
        <!--
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameLocalHighScoresJavaLibraryTs</artifactId>
            <version>${allbinary.platform.version}</version>
            <optional>true</optional>
        </dependency>
        -->
        
        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AllBinaryToAdvancedMin3dJavaLibraryTs</artifactId>        
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.media.graphics.geography.map</groupId>
            <artifactId>GeographicMapLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.mapeditor</groupId>
            <artifactId>TiledJSONJavaLibraryTs</artifactId>
            <version>1.4.2-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpTs</artifactId>
            <version>2.0.4</version>
            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>OpenGLESJOGLJavaLibraryTs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>        

        <dependency>
            <groupId>org.khronos</groupId>
            <artifactId>opengl-apiTs</artifactId>
            <version>gl1.1-android-2.1_r1</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>

        <plugins>
                <!--    <version>1.15.4</version>-->
                <!--    <version>1.14.2</version>-->
                    <!-- set the path to node - make sure the version is the same as in the config-->
                    <!--   <workingDirectory>${YOUR_WORKING_DIRECTORY}</workingDirectory>-->
                    <!--                <nodeVersion>v16.14.0</nodeVersion>-->
<!--
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <installDirectory>C:\</installDirectory>
                    <nodeVersion>v25.9.0</nodeVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and yarn</id>
                        <goals>
                            <goal>install-node-and-yarn</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm run validation</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run validate</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
-->




            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
        
    </build>

</project>

