<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.allbinary.game.gd</groupId>
  <artifactId>GDJavaLibraryTs</artifactId>
  <packaging>jar</packaging>
  <!-- AllBinary Platform Version Start -->
  <version>1.0.0-SNAPSHOT</version>
  <!-- AllBinary Platform Version End -->

  <name>GDJavaLibraryTs</name>
  <url>http://www.allbinary.com/</url>
    <distributionManagement>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <name>AllBinary Snapshots Nexus</name>
            <url>https://nexus-allbinary.rhcloud.com/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>nexus-releases</id>
            <name>AllBinary Releases Nexus</name>
            <url>https://nexus-allbinary.rhcloud.com/nexus/content/repositories/releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <buildLabel>${project.version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
    </properties>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingJ2MEAllTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LogJ2SEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>PreGameJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FileJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>jsonTs</artifactId>
            <!-- 20210307, 20210307_1.3 -->
            <!-- AllBinary Platform Version Start -->
            <version>20230227</version>
            <!-- AllBinary Platform Version End -->

        </dependency>

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpTs</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>

        <plugins>

                <!--    <version>1.15.4</version>-->
                <!--    <version>1.14.2</version>-->
                    <!-- set the path to node - make sure the version is the same as in the config-->
                    <!--   <workingDirectory>${YOUR_WORKING_DIRECTORY}</workingDirectory>-->
                    <!--                <nodeVersion>v16.14.0</nodeVersion>-->
<!--
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <installDirectory>C:\</installDirectory>
                    <nodeVersion>v25.9.0</nodeVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and yarn</id>
                        <goals>
                            <goal>install-node-and-yarn</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm run validation</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run validate</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
-->


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-assembly-pluginTs</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>single</goal></goals>
                    </execution>
                </executions>
                <configuration>
                    <attach>true</attach>
                    <descriptors>
                        <descriptor>assembly.xml</descriptor>
                    </descriptors>

                </configuration>
            </plugin>
        </plugins>

    </build>

</project>

