<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentKt</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version End -->
    </parent>

    <artifactId>GDGameThreedAndroidJavaLibraryKt</artifactId>
    <packaging>jar</packaging>

    <name>GDGameThreedAndroidJavaLibraryKt</name>
    <url>http://www.allbinary.com/</url>
    <distributionManagement>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <name>AllBinary Snapshots Nexus</name>
            <url>https://nexus-allbinary.rhcloud.com/nexus/content/repositories/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>nexus-releases</id>
            <name>AllBinary Releases Nexus</name>
            <url>https://nexus-allbinary.rhcloud.com/nexus/content/repositories/releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <buildLabel>${project.version}</buildLabel>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingJ2MEAllKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LogJ2MEJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOptionalBasePlatformJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MotionInputAndroidResourcesJavaLibraryKt</artifactId>        
            <version>${allbinary.platform.version}</version>
            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MusicAndroidJavaLibraryKt</artifactId>
            <!-- 
            <artifactId>MusicJ2MEJavaLibraryKt</artifactId>
            <artifactId>MusicAndroidJavaLibraryKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
                
        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>TouchButtonResourceOpenGLESAnimationJavaLibraryKt</artifactId>
            <version>${allbinary.platform.version}</version>
            <optional>true</optional>
        </dependency> 

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>OpenGLESAndroidJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AndroidToMin3dJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>min3d</groupId>
            <artifactId>Min3dForAndroidPlatformJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedAndroidResourcesTempJavaLibraryKt</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <optional>true</optional>            
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedAndroidResourceJavaLibraryKt</artifactId>        
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameOpenGLThreedAnimationResourceJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>        

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameBaseJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameAndroidResourcesTempJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameAndroidSoundsJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <!--
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDJavaLibraryKt</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        -->

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpKt</artifactId>
            <version>2.0.4</version>
            <optional>true</optional>
        </dependency>
                
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>androidKt</artifactId>        
            <version>4.1.1.4</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>2.4.0-RC</version><!-- kotlin -->
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>2.4.0-RC</version><!-- kotlin -->
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass></mainClass>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>

