<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentTsJs</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version End -->
    </parent>

    <artifactId>GDGameGeneratedPTsJs</artifactId>
    <packaging>pom</packaging>
    <name>GDGameGeneratedPTsJs</name>
    <url>http://maven.apache.org</url>

    <properties>
        <buildLabel>${version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
    </properties>

    <modules>

        <!--
        -->
 
        <module>../GDJavaLibraryTsJsM</module>

        <module>../resource/GDGameResourceJavaLibraryTsJsM</module>
        <module>../resource/GDGameImageAnimationInterfaceResourceFactoryJavaLibraryTsJsM</module>
<!--        <module>../resource/GDGameAndroidImageAnimationInterfaceResourceFactoryJavaLibraryTsJsM</module>-->
        <!--
        <module>../resource/GDGameOpenGLESImageAnimationInterfaceResourceFactoryJavaLibraryTsJsM</module>
        -->
        
        <module>../GDGameBaseJavaLibraryTsJsM</module>
        <!--
        <module>../GDGameThreedBaseJavaLibraryTsJsM</module>
        -->

        <module>../GDGameWavSoundsJavaLibraryTsJsM</module>
        
        <module>../platform/android/GDGameAndroidResourceJavaLibraryTsJsM</module>
        
        <module>../platform/android/GDGameAndroidJavaLibraryTsJsM</module>
        <!--
        <module>../platform/android/GDGameThreedAndroidBaseJavaLibraryTsJsM</module>
        -->
    </modules>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        
    </dependencies>

</project>



