<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentJs</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version End -->
    </parent>

    <artifactId>GDGameGeneratedPJs</artifactId>
    <packaging>pom</packaging>
    <name>GDGameGeneratedPJs</name>
    <url>http://maven.apache.org</url>

    <properties>
        <buildLabel>${version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
    </properties>

    <modules>

        <!--
        -->
 
        <module>../GDJavaLibraryJsM</module>

        <module>../resource/GDGameResourceJavaLibraryJsM</module>
        <module>../resource/GDGameImageAnimationInterfaceResourceFactoryJavaLibraryJsM</module>
<!--        <module>../resource/GDGameAndroidImageAnimationInterfaceResourceFactoryJavaLibraryJsM</module>-->
        <!--
        <module>../resource/GDGameOpenGLESImageAnimationInterfaceResourceFactoryJavaLibraryJsM</module>
        -->
        
        <module>../GDGameBaseJavaLibraryJsM</module>
        <!--
        <module>../GDGameThreedBaseJavaLibraryJsM</module>
        -->

        <module>../GDGameWavSoundsJavaLibraryJsM</module>
        
        <module>../platform/android/GDGameAndroidResourceJavaLibraryJsM</module>
        
        <module>../platform/android/GDGameAndroidJavaLibraryJsM</module>
        <!--
        <module>../platform/android/GDGameThreedAndroidBaseJavaLibraryJsM</module>
        -->
    </modules>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        
    </dependencies>

</project>


