<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.allbinary.game.gd</groupId>
    <artifactId>GDGameOpenGLThreedAnimationResourceJavaLibraryJs</artifactId>
    <packaging>jar</packaging>
    <!-- AllBinary Platform Version Start -->
    <version>1.0.0-SNAPSHOT</version>
    <!-- AllBinary Platform Version End -->
    <name>GDGameOpenGLThreedAnimationResourceJavaLibraryJs</name>
    <url>http://maven.apache.org</url>

    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingJ2MEAllJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LogJ2SEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ProgressJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>J2MEForJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>        

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ImageCacheJ2MEJavaLibraryJs</artifactId>
<!-- 
            <artifactId>ImageCacheLazyJ2MEJavaLibraryJs</artifactId>
            <artifactId>ImageCacheJ2MEJavaLibraryJs</artifactId>
-->
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>        

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ImageCacheOpenGLESJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>CommonHeadsUpDisplayLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>WeaponMineJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game</groupId>
            <artifactId>LifeOrDeathDataJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.animation</groupId>
            <artifactId>AllBinaryImageAnimationJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.animation</groupId>
            <artifactId>AllBinaryImageAnimationRotationJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.animation</groupId>
            <artifactId>AllBinarySpriteAnimationJavaLibraryJs</artifactId>      
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
      
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameConfigurationJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
  
        <dependency>
            <groupId>org.allbinary.game.threed</groupId>
            <artifactId>AllBinaryToAdvancedMin3dJavaLibraryJs</artifactId>        
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedBaseJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameThreedPreBaseJavaLibraryJs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameOpenGLTwoDJ2SEImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
<!--
                <artifactId>GDGameOpenGLTwoDJ2SEImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
                <artifactId>GDGameOpenGLTwoDLazyJ2SEImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
-->
            <version>1.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

        <!--
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameImageAnimationInterfaceResourceFactoryJavaLibraryJs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        -->
                
        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpJs</artifactId>
            <version>2.0.4</version>
            <optional>true</optional>
        </dependency>
        
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>androidJs</artifactId>
            <version>1.6_r2</version>
            <scope>provided</scope>
        </dependency>          
    </dependencies>
  
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <id>npm-install-typescript</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <arguments>
                                <argument>/c</argument>
                                <argument>npm</argument>
                                <argument>install</argument>
                                <argument>typescript</argument>
                                <argument>--no-save</argument>
                                <argument>--no-audit</argument>
                                <argument>--no-fund</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tsc-compile</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <!-- Uses the path from tsconfig.json instead of -p path; ignore tsc errors so the build continues -->
                            <arguments>
                                <argument>/c</argument>
                                <!--                                <argument>npx tsc</argument>-->
                                <argument>npx tsc || exit 0</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.1.2</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>



            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

