<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParent</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>
        
    <groupId>org.allbinary.game.gd</groupId>
    <artifactId>GDGameHTMLResourcesJavaLibraryJs</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <packaging>jar</packaging>

    <name>GDGameHTMLResourcesJavaLibraryJs</name>
    <url>http://www.allbinary.com/</url>

    <properties>

        <!--
        Currently individual games copy the resources.
        -->
        <!--
        <outputPath>../GDGamePlayNWarM/war/gd/</outputPath>
        <inputPath>..\..\..\Resources\images\release\</inputPath>
        <inputPath2>..\..\..\Resources\images\wait\</inputPath2>
        <inputPath5>..\..\..\Resources\images\gd\</inputPath5>
        <inputPath3>..\..\..\Resources\sounds\release\</inputPath3>
        -->

        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>         

        <!--
        <dependency>
            <groupId>org.allbinary.game.resources</groupId>
            <artifactId>GameSoundsWavResourcesJavaLibraryJs</artifactId>
            <version>${allbinary.platform.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.resources</groupId>
            <artifactId>GameImageLowResourcesJavaLibraryJs</artifactId>
            <version>${allbinary.platform.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.resources</groupId>
            <artifactId>GameImageMediumResourcesJavaLibraryJs</artifactId>
            <version>${allbinary.platform.version}</version>
        </dependency>
        -->
        
    </dependencies>

    <build>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <id>npm-install-typescript</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <arguments>
                                <argument>/c</argument>
                                <argument>npm</argument>
                                <argument>install</argument>
                                <argument>typescript</argument>
                                <argument>--no-save</argument>
                                <argument>--no-audit</argument>
                                <argument>--no-fund</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tsc-compile</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>cmd</executable>
                            <workingDirectory>${basedir}</workingDirectory>
                            <!-- Uses the path from tsconfig.json instead of -p path; ignore tsc errors so the build continues -->
                            <arguments>
                                <argument>/c</argument>
                                <!--                                <argument>npx tsc</argument>-->
                                <argument>npx tsc || exit 0</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>

