<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentKt</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>

    <artifactId>GDGameJ2MEKt</artifactId>
    <packaging>jar</packaging>

    <name>GDGameJ2MEKt</name>
    <url>http://www.allbinary.com/</url>

    <properties>
        <inputPath2>src\main\java\</inputPath2>
        <inputPath>target\dependency\</inputPath>
        <outputPath>..\..\..\platformx\j2me\GDGameJ2MEApplicationM\src\main\java\</outputPath>
    </properties>

    <dependencies>
        <!--
-        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        -->

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingJ2MEAllKt</artifactId>
            <!--
            <artifactId>LoggingHTMLAllKt</artifactId>
            <artifactId>LoggingNoneKt</artifactId>
            <artifactId>LoggingHTML5ExceptionKt</artifactId>
            <artifactId>LoggingRemoteExceptionKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOnJ2MEPlatformJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AdvertisementClientNoneJavaLibraryKt</artifactId>
            <!--
            <artifactId>AndroidAdvertisementJavaLibraryKt</artifactId>            
            <artifactId>AdvertisementClientNoneJavaLibraryKt</artifactId>           
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameAndroidAdvertisementJavaLibraryKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.multiplayer</groupId>
            <artifactId>AllBinaryGameClientBaseNullJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameLicensingOnlyDemoJavaLibraryKt</artifactId>
            <!--
                <artifactId>GameLicensingOnlyNormalJavaLibraryKt</artifactId>
                <artifactId>GameLicensingOnlyDemoJavaLibraryKt</artifactId>
                <artifactId>GameLicensingInAppPurchaseJavaLibraryKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoTouchButtonJavaLibraryKt</artifactId>
            <!--
            <artifactId>NoTouchButtonJavaLibraryKt</artifactId>
            <artifactId>TouchButtonMappingJavaLibraryKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>NoTouchButtonResourceAnimationJavaLibraryKt</artifactId>
            <!--
            <artifactId>NoTouchButtonResourceAnimationJavaLibraryKt</artifactId>
            <artifactId>TouchButtonResourceAnimationJavaLibraryKt</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameNoTouchJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
            <!--
            <artifactId>GDGameNoTouchJavaLibraryKt</artifactId>
            <artifactId>GDGameTouchJavaLibraryKt</artifactId>
            -->
        </dependency>
                
        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGamePCClientInfoJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameJ2MEJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameBaseJavaLibraryKt</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>1.0.0-SNAPSHOT</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <!--        
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MotionGestureJavaLibraryKt</artifactId>
            
        </dependency>
        -->

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpKt</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>
    
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>2.4.0-RC</version><!-- kotlin -->
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-pluginKt</artifactId>
                <executions>
                    <execution>
                        <id>sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
                            <!--
                            <outputDirectory>${project.build.directory}/sources</outputDirectory>
                            -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Delete output directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-pluginKt</artifactId>
                <version>2.4.1</version>
                <configuration>
                    <followSymLinks>false</followSymLinks>
                    <filesets>
                        <fileset>
                            <directory>${outputPath}</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
      
            <plugin>
                <artifactId>maven-resources-pluginKt</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${outputPath}</outputDirectory>
                            <resources>          
                                <resource>
                                    <directory>${inputPath}</directory>
                                    <filtering>false</filtering>
                                </resource>
                                <resource>
                                    <directory>${inputPath2}</directory>
                                    <filtering>false</filtering>
                                </resource>
                                <!--
                                -->                
                            </resources>              
                        </configuration>            
                    </execution>
                </executions>
            </plugin>
            
        </plugins>

    </build>

</project>

