<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--
    <parent>
        <groupId>org.allbinary.gwt.forplayn</groupId>
        <artifactId>AllBinaryPlaynGWT</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
-->
    <groupId>org.allbinary.game.gd</groupId>
    <artifactId>GDGame2JsHTMLTemp</artifactId>
    <name>GDGame2JsHTMLTemp</name>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
    </properties>

    <dependencies>
   
        <!-- All of the Java that needs GWT conversion while some includes JsInterop Mapping -->

    </dependencies>
        
    <build>
        <sourceDirectory>src</sourceDirectory>

        <plugins>            
      
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>

        <resources>
            <resource>
                <directory>${basedir}/src</directory>
            </resource>
        </resources>
                    
    </build>
</project>

