<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParent</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>

    <artifactId>GDGameJ2MEJavaLibraryTs</artifactId>
    <packaging>jar</packaging>

    <name>GDGameJ2MEJavaLibraryTs</name>
    <url>http://www.allbinary.com</url>    

    <properties>
        <buildLabel>${version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOptionalBasePlatformJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MusicJ2MEJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>
                
        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>TouchButtonResourceAnimationJavaLibraryTs</artifactId>
            <!--
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>        

        <dependency>
            <groupId>org.allbinary.input</groupId>
            <artifactId>TouchButtonResourceOpenGLESAnimationJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>        

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameNoTouchJavaLibraryTs</artifactId>
            <!--
            <artifactId>GDGameTouchJavaLibraryTs</artifactId>
            <artifactId>GDGameNoTouchJavaLibraryTs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->

            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameImageAnimationInterfaceResourceFactoryJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameOpenGLESImageAnimationInterfaceResourceFactoryJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameWavSoundsJavaLibraryTs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        
        <!-- Only to get maven to download it unless alread in repo from build -->
<!--        <dependency>
            <groupId>net.sf.antenna</groupId>
            <artifactId>antennaTs</artifactId>
            <version>1.2.1-beta-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>-->

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpTs</artifactId>
            <version>2.0.4</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>npm-install</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>2.0.0</version>
                        <configuration>
                            <installDirectory>c:\</installDirectory>
                            <nodeVersion>v26.7.0</nodeVersion>
                            <npmVersion>12.0.0</npmVersion>
                            <testFailureIgnore>true</testFailureIgnore>
                        </configuration>
                        <executions>
                            <execution>
                                <id>install node and npm</id>
                                <goals>
                                    <goal>install-node-and-npm</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>npm install</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <configuration>
                                    <arguments>install</arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>

            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <installDirectory>c:\</installDirectory>
                    <nodeVersion>v26.7.0</nodeVersion>
                    <npmVersion>12.0.0</npmVersion>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
                <executions>
                    <execution>
                        <id>npm run validation</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run validate</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
                        
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.1.2</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>

