<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
        
    <parent>
        <groupId>org.allbinary.game.gd</groupId>
        <artifactId>GDGameParentJs</artifactId>
        <!-- Game Version Start -->
        <version>1.0.0-SNAPSHOT</version>
        <!-- Game Version Start -->
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>GDGameTouchHTMLJs</artifactId>
    <packaging>jar</packaging>
    <name>GDGameTouchHTMLJs</name>
    <url>http://maven.apache.org</url>

    <properties>
        <buildLabel>${version}</buildLabel>
        <assemblyPluginVersion>2.2-beta-1</assemblyPluginVersion>
    </properties>


    <properties>
        <yarnVersion>v1.22.22</yarnVersion>
    </properties>

    <dependencies>
        <!--
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        -->

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>LoggingHTMLAllJs</artifactId>
            <!--
            <artifactId>LoggingHTML5AllJs</artifactId>
            <artifactId>LoggingNoneJs</artifactId>
            <artifactId>LoggingHTML5ExceptionJs</artifactId>
            <artifactId>LoggingRemoteExceptionJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AdvertisementClientNoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.multiplayer</groupId>
            <artifactId>AllBinaryGameClientBaseNullJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MotionGestureBaseJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchScreenJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>TouchJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>AllBinaryOnHTMLPlatformJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <exclusions>
                <exclusion>
                    <groupId>org.allbinary</groupId>
                    <artifactId>FullScreenJavaLibraryJs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FullScreenNoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>ScreenCaptureNoneJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>MicroEmulatorCustomUIJavaLibraryJs</artifactId>
            <!--
            <artifactId>MicroEmulatorCustomUIJavaLibraryJs</artifactId>
            <artifactId>NullCustomUIJavaLibraryJs</artifactId>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>


        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>NoGameLicensingJavaLibraryJs</artifactId>
        <!--
            <artifactId>NoGameLicensingJavaLibraryJs</artifactId>
            <artifactId>LicensedGameDemoJavaLibraryJs</artifactId>
        -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
        <!--
            <artifactId>GameLicensingOnlyNormalJavaLibraryJs</artifactId>
            <artifactId>GameLicensingOnlyDemoJavaLibraryJs</artifactId>
        -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>HardCodedLicenseInitInfoJavaLibraryJs</artifactId>
            <!--
            <artifactId>HardCodedLicenseInitInfoJavaLibraryJs</artifactId>
            <artifactId>FileLicenseInitInfoJavaLibraryJs</artifactId>

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>FileJ2SEJavaLibraryJs</artifactId>
        </dependency>
            -->
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

<!--
        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>BouncyCastleDESJavaLibraryJs</artifactId>
-->
<!--
            <artifactId>BouncyCastleDESJavaLibraryJs</artifactId>
            <artifactId>YourSecurityJavaLibraryJs</artifactId>
-->
<!--            <version>${allbinary.platform.version}</version>-->
<!--            <scope>provided</scope>-->
<!--
        </dependency>
-->

        <dependency>
            <groupId>org.allbinary</groupId>
            <artifactId>VectorAnimationJ2MEJavaLibraryJs</artifactId>
            <!-- AllBinary Platform Version Start -->
            <version>${allbinary.platform.version}</version>
            <!-- AllBinary Platform Version End -->
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGamePCClientInfoJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameHTMLJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.allbinary.game.gd</groupId>
            <artifactId>GDGameBaseJavaLibraryJs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.microemu</groupId>
            <artifactId>microemu-midpJs</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-pluginJs</artifactId>
                <executions>
                    <execution>
                        <id>sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <failOnMissingClassifierArtifact>false</failOnMissingClassifierArtifact>
                            <!--
                            <outputDirectory>${project.build.directory}/sources</outputDirectory>
                            -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>

